# Generated by Django 3.0.8 on 2020-08-25 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, verbose_name='date of creation')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField()),
                ('img', models.CharField(max_length=32)),
                ('price', models.IntegerField()),
                ('level', models.SmallIntegerField(choices=[('1', 'Easy'), ('2', 'Normal'), ('3', 'Hard')], default='1')),
                ('authors', models.ManyToManyField(related_name='authors', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='students', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='mainapp.Tag')),
            ],
        ),
    ]
