# Generated by Django 3.0.8 on 2020-08-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20200825_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooluser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users/photo/'),
        ),
    ]
