# Generated by Django 3.0.8 on 2020-08-25 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('link', models.URLField(blank=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LessonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Course')),
                ('materials', models.ManyToManyField(to='courseapp.AdditionalMaterial')),
            ],
        ),
        migrations.CreateModel(
            name='InteractiveLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typing_text', models.TextField(verbose_name='Typing text (format: xxxxxx.xxxxxx.xxxxxx)')),
                ('second_limit', models.PositiveSmallIntegerField(null=True)),
                ('error_limit', models.PositiveIntegerField(null=True)),
                ('lesson_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courseapp.LessonInfo')),
            ],
        ),
    ]
