# Generated by Django 3.0.8 on 2020-08-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalmaterial',
            name='file',
            field=models.FileField(upload_to='courses/lessons/'),
        ),
    ]
