# Generated by Django 3.0.8 on 2020-08-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_auto_20200825_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalmaterial',
            name='file',
            field=models.FileField(blank=True, upload_to='courses/lessons/'),
        ),
    ]
